name: Autonomous Tests

on:
  workflow_dispatch:
    inputs:
      test_duration:
        description: 'Test duration in seconds'
        required: true
        default: '120'
        type: string
      target_url:
        description: 'Target website URL'
        required: true
        default: 'https://www.leasingmarkt.de'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install chromium
        python -m playwright install-deps

    - name: Run autonomous tests
      run: |
        mkdir -p reports
        python3 -m src.bot.autonomous_lm_test_2_min --duration ${{ github.event.inputs.test_duration }} --url ${{ github.event.inputs.target_url }}
      env:
        PLAYWRIGHT_HEADLESS: "true"

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: reports/*.html
        retention-days: 14

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      id: deployment
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
