name: Nightly Autonomous Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-autonomous-tests:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        
    - name: Install Playwright browsers
      run: |
        python -m playwright install chromium
        python -m playwright install-deps
        
    - name: Run autonomous tests
      run: |
        mkdir -p reports
        python3 -m src.bot.autonomous_lm_test_2_min
      env:
        PLAYWRIGHT_HEADLESS: "true"
        
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: reports/*.html
        retention-days: 14
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './reports'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
